# Generated by Django 3.0.7 on 2020-07-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
